### ISSUE TITLE
Installer not working on clean Ubuntu 16.04.2

### ISSUE THREAD

**Issue by verglor** [serverscope/serverscope-benchmark#21]
Installer is not working on clean Ubuntu 16.04.2 (at Hetzner) out of the box:

```
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.8.0-45-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
root@Ubuntu-1604-xenial-64-minimal ~ # bash <(curl -sSL https://raw.githubusercontent.com/serverscope/serverscope-benchmark/master/install-serverscope.sh) -uvc -e "example@example.com" -p "PX60-SSD|Hetzner"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-minimal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libpython-stdlib
Can not install dependencies automatically.
```

```apt-get update``` has to be manually executed beforehand.

**Comment by anton-ko** [comment]
Hey @jako512, 
Thanks for posting it here.

I think I know what's going on.. the script installs python first and then the rest of the dependancies.

see https://github.com/serverscope/serverscope-benchmark/blob/master/install-serverscope.sh#L95, lines 95 and 98.

Should be a simple fix. Thanks for bringing this to my attention.

**Comment by verglor** [comment]
@anton-ko Do you plan to fix it ?

**Comment by anton-ko** [comment]
@verglor yes, definitely. I'm not in position to provide you with a timeframe though. I hope to be able to work on this and some other issues in a few weeks once I close off some other projects. 

Thanks for letting me know that people are still waiting on a fix here. I appreciate all the support. 

Feel free to submit a PR if you have the time. 
Thanks.
