### ISSUE TITLE
Error when upload test's results

### ISSUE THREAD

**Issue by vvatitv** [serverscope/serverscope-benchmark#25]
Hello, 

When server finish your test, i see this error... when attempting upload result to your site...

![12f4eeb0adb1b2d6fe1507d553bf0cce](https://user-images.githubusercontent.com/16290435/35317182-9489aa5c-00e6-11e8-891a-5eecdeaea418.png)

PS. OS Debian 9 / Ubuntu 16.04

**Comment by anton-ko** [comment]
Hey @vvatitv 

Thanks for reaching out. Sorry, it didn't work for you.

based on the error message I see ("Network is unreachable"), it seems like your server can't connect to ServerScope.io..

Could you try running `curl -I https://serverscope.io` to see if the network is working properly?
If you're getting status 200 and no errors, could you please try running benchmark again?

You can check off some of the tests to make it run faster.

**Comment by vvatitv** [comment]
Hello,

Yes, i think, that it server...
I restarted the test more than 4 times, but error message i get constantly... I don't know why this is happening and I refused server....

**Comment by anton-ko** [comment]
Hey @vvatitv 

Yeah, based on the error message, your server couldn't connect to serverscope.io.
We get corrupted benchmark reports sometimes but in that case, you'd see a different error and I would get an error notification.

So, it might be some kind of network issue or a firewall.
Could you share the hosting provider name? 

I could see if we have any other submissions from their servers and, if I get a chance, even get a VPS from them and try to troubleshoot.

Thanks!

**Comment by vvatitv** [comment]
@anton-ko 

Provider: smartape.ru
Location: Russia

:)

**Comment by anton-ko** [comment]
Perfect, thanks!
I'm going to close this issue since there is not much I can do at this point.
Thanks for submitting it though. It's nice to know what's going on.

We'll see if there are other providers from Russia that affected by the connection issue.
