### ISSUE TITLE
Dependency on `which`

### ISSUE THREAD

**Issue by anton-ko** [serverscope/serverscope-benchmark#26]
From an email:

On several of my Centos 7.5 VPS', I needed to manually install 'which' before your script would work properly. You might want to add that as a dependency or work around it. It might not be part of Centos minimal install, which is usual template for Centos 7 VPS', typically

**Comment by plageat** [comment]
Done in https://github.com/plageat/serverscope-benchmark/commit/ce59531ef759ff17f1395d67a4bf26c92e957327
