### ISSUE TITLE
How to clean and uninstall?

### ISSUE THREAD

**Issue by Leonardo-Fiori** [serverscope/serverscope-benchmark#29]
The bash command i ran from console failed. How can i clean the stuff that has been downloaded?

**Comment by ukguy** [comment]
same question here, can't find an uninstall or remove command

**Comment by MikeSchroll** [comment]
I always:
`docker run -it —rm ubuntu:18.04 /bin/bash`
apt-get update
apt install -y curl

Then paste the serverscope command

That way it doesn’t leave any residue in my host.

**Comment by plageat** [comment]
ATM just use one of the following:

**el8:**

`dnf erase python3-serverscope_benchmark`

**el7:**

`yum erase python36-serverscope_benchmark` 

**Debian/Ubuntu:**

`apt remove python3-serverscope-benchmark`
