### ISSUE TITLE
Which ioengine are you using?

### ISSUE THREAD

**Issue by sitsofe** [serverscope/serverscope-benchmark#30]
Over on https://github.com/serverscope/serverscope-benchmark/blob/df6ecb15931cdfffaa18ce0409d6c229d7231310/serverscope_benchmark/benchmarks.py#L140 I see you are setting the `iodepth` to greater than one in some cases but this [only makes sense if the `ioengine` you are using is asynchronous](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-iodepth) (except in a special verification case). Keep an eye on the [reported depths achieved in fio's output](https://fio.readthedocs.io/en/latest/fio_man.html#interpreting-the-output) to verify this...

**Comment by anton-ko** [comment]
Good catch!

This is correct. The benchmark used to call for `libaio` but it would show unrealistically slow speeds in some common VM configurations (0.1-0.5 mb/s). Quite a few people complained so I ended up switching to the default io engine which IIRC is synchronous. So, the `iodepth` flag is probably an artifact of that.

Feel free to reopen if you have any follow-up questions.

**Comment by sitsofe** [comment]
"Unrealistically slow" - well, um, I'd argue it was realistically slow ;-) You've got to bear in mind that block size is teeny tiny (4k) so if there's no buffering it's just going to be slow because the (network) disk really is just that slow! I suppose it's not impossible that such disk support a high queue depth (64 or higher) which might cover help to cover up the higher latency costs involved...

Having said all the above, the brutal reality is that if you're going through a filesystem (which I can tell these tests are doing) then you're at the mercy of how well that filesystem copes with direct I/O.  Some filesystems just ignore the hint (see https://stackoverflow.com/a/46377629/ for caveats that make libaio synchronous and thus cripple performance) in which case they may give wildly "unrealistic" results in comparison to better well behaved filesystems when it comes to writes. I'd say just do buffered I/O everywhere and on jobs that are doing writes use [`end_fsync=1`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-end-fsync) so you know the data isn't just sitting in the kernel cache rather than using `direct=1` but I'm just a random on the internet :-)

NB: [`invalidate` already defaults to on](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-invalidate) by default.

**Comment by anton-ko** [comment]
You make great points. I remember asking for opinions on the topic somewhere on the internet before and I wish somebody chimed in with something like this.

I like the idea of using buffered I/O and `end_fsync`. This seems like an approach that could yield more useful numbers for comparison between different setups. 

I'll have to think it over but it sounds like something I would want to introduce in the next version.
Thanks!

If you've got any more suggestions/feedback, please share 🙃

**Comment by sitsofe** [comment]
> If you've got any more suggestions/feedback, please share 🙃

Typically you try and arrange for I/O to be sent to disk in much greater sizes than 4K. Even if a program thinks it's only doing multiple 128 bytes writes there's typically a lot of buffering going on (at the C-library level then again at the kernel level) to try and group I/O together before hitting disk and C-library level buffering won't be done by `fio`. Additionally the bigger the I/O you send down the less work that has to be done for the same bandwidth. There's an argument to (also) choose block sizes in the 16k-64k range so you may want to show results with a range of I/O. It all depends on what you're trying to measure - is it the disk or a particular filesystem or how you are sending a type of I/O etc (http://www.brendangregg.com/ActiveBenchmarking/bonnie++.html has some discussion on this).

Because you're using `numjobs` you'll get I/O parallelism through that even though `iodepth` might be set to 1. The question is whether that's enough parallelism... it looks like you're only using a value of 8 and things like SATA disks have queues of around 32 and NVMe disks have have queues in the 100s!

Writing zeros (as you are doing with `dd`) can be a special case (see https://github.com/axboe/fio/issues/711 for someone else's experience with this). It doesn't happen that frequently in critical paths of normal day to day operation but when I have seen it happen (e.g. when creating a eager zero backing volume on ESXi) it's usually a one off first time operation. Due it's nature various parts of the stack (e.g. filesystem, SSD disk) may in turn have a special case path for it thus creating a number you never see with real data. Even if there's no "detect zeroes" path things like compression can really reduce the amount of work that has to be done with straight zeros.`fio` randomises the data in its initial buffer which helps defeat this but if you HAVE to defeat strong compression (most don't) for your benchmark you may need even more sophisticated options (see [`refill_buffers`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-refill-buffers) and similar).

You're not doing this but if you are trying to scrape fio output (e.g. to log to a database and plot results) please use one of the machine output formats (preferably `json` but `terse` is also OK). See https://www.youtube.com/watch?v=vm1GJMp0QN4#t=17m48s for an example of where scraping the human readable output went wrong.
